In [ ]:
#Proviamo a normaliizzare i dati:

# Normalizzazione manuale
def min_max_normalize(data):
    # Calcola il minimo e il massimo per ogni colonna
    data_min = np.min(data, axis=0)
    data_max = np.max(data, axis=0)
    
    # Applica la formula della normalizzazione
    normalized_data = (data - data_min) / (data_max - data_min)
    return normalized_data


# Separa le feature (X) e le etichette (y)
X = manuale.iloc[:, :-1].values  # Tutte le colonne tranne l'ultima (feature)
y = manuale.iloc[:, -1].values    # L'ultima colonna (target)

normalized_manuale = min_max_normalize(X)
print("Dati Normalizzati:\n", normalized_manuale)

#applichiamo knn sul dataset normalizzato:


# Esegui la ricerca del miglior valore di k
k_values = list(range(1, 11))  # Prova k da 1 a 10
best_k = find_best_k(X, y, k_values, num_folds=5)  # Cross-validation a 5 fold

# Valutazione finale: Usa il miglior k trovato per fare predizioni su tutto il dataset
y_final_pred = knn_predict(normalized_manuale, y, normalized_manuale, best_k)

# Calcola e stampa l'accuratezza finale usando lo stesso dataset
final_accuracy = np.mean(y_final_pred == y)
print(f'Accuratezza finale sui dati (con k={best_k}): {final_accuracy:.4f}')



Dati Normalizzati:
 [[0.375      0.85714286 0.6        0.11764706 0.         0.83333333]
 [0.625      1.         0.8        0.08823529 0.         0.16666667]
 [0.475      0.28571429 0.4        0.01470588 0.5        0.58333333]
 [0.5        1.         0.7        0.         0.         0.16666667]
 [0.625      0.71428571 0.2        0.79411765 0.         0.41666667]
 [0.325      1.         0.6        0.88235294 0.         0.16666667]
 [0.325      0.85714286 0.4        0.88235294 0.         0.5       ]
 [0.625      0.21428571 0.2        0.05882353 1.         0.83333333]
 [0.55       0.71428571 0.8        0.91176471 0.         0.16666667]
 [0.8        0.85714286 0.6        0.16176471 0.         0.16666667]
 [0.325      0.28571429 0.2        0.88235294 0.         0.41666667]
 [0.225      0.71428571 0.6        0.         0.         0.16666667]
 [0.375      0.57142857 0.78       0.88235294 0.         0.45833333]
 [0.25       0.71428571 0.5        0.88235294 0.5        0.16666667]
 [0.95       0